import { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [linkData, setLinkData] = useState({ data: 'is empty right now', detail: 'will show when fetched' })
  const [link, setLink] = useState('')
  const [validLink, setValidLink] = useState('https://www.youtube.com/watch?v=MejbOFk7H6c')

  const isValidUrl = urlString => {
    var urlPattern = new RegExp('^(https?:\\/\\/)?' + // validate protocol
      '((([a-z\\d]([a-z\\d-]*[a-z\\d])*)\\.)+[a-z]{2,}|' + // validate domain name
      '((\\d{1,3}\\.){3}\\d{1,3}))' + // validate OR ip (v4) address
      '(\\:\\d+)?(\\/[-a-z\\d%_.~+]*)*' + // validate port and path
      '(\\?[;&a-z\\d%_.~+=-]*)?' + // validate query string
      '(\\#[-a-z\\d_]*)?$', 'i'); // validate fragment locator
    return !!urlPattern.test(urlString);
  }

  useEffect(() => {
    const fetchLinkData = async () => {
      const response = await fetch(`/api/getmetadata?url=${validLink}`);
      const data = await response.json();
      console.log(data);
      setLinkData(data)
    }

    fetchLinkData()
  }, [link])

  const onLinkChange = (e) => {
    const newLink = e.target.value;
    if (!isValidUrl(newLink)) {
      setLink(newLink); return;
    }
    setLink(newLink);
    setValidLink(newLink);
    console.log(newLink)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>Showing data for: {validLink}</p>
        <input value={link} type='text' onChange={onLinkChange} className={styles.input} />
        {/* <pre>
          <code className={styles.code}>
            {JSON.stringify(linkData, null, 2)}
          </code>
        </pre> */}
        <p>
          {JSON.stringify(linkData, null, 2)}
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
